import { Song } from "../types/song";

export const songs :Song[] = [
  { artist: "King Gizzard and the Lizard Wizard", name: "Planet B", youtubeId: "PJtTs21nlgcFWgQc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hypertension", youtubeId: "BDJ3nQAanMA" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Dusk To Dawn On Lygon Street", youtubeId: "OquboEr0FiiZQOos" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Mystery Jack", youtubeId: "LXjvgKDhYIk2tq97" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Ugly Guitars", youtubeId: "Y2eKaSjdvyU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Evilest Man", youtubeId: "cDGvduVEweg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Bloody Ripper", youtubeId: "WY0OUbEbLBI1vX3U" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Grim Reaper", youtubeId: "dsNawHKvYYU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Pop In My Step", youtubeId: "YcMuXleRf_H7tWAr" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Vomit Coffin", youtubeId: "uXKurQqM0zWKWaAv" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Muddy Water", youtubeId: "kvb47SJq9wtFPj88" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Blue Morpho", youtubeId: "_4pi9COoTNk" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Tezeta", youtubeId: "V1CejFSSHzxHnS_A" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Good To Me", youtubeId: "BwQZkjITfBk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Die To", youtubeId: "hW9OP_mKGTY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Kill Bad People To", youtubeId: "cf7zsjLcakQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Eddie Cousin", youtubeId: "1mbsfpCm-wQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Work This Time", youtubeId: "XiSY8kuknD9Qqp40" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Trench Foot", youtubeId: "ytP7UE3a0nw" },
  { artist: "King Gizzard and the Lizard Wizard", name: "N.G.R.I. (Bloodstain)", youtubeId: "9g4x_EZtai0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Time = $$$", youtubeId: "-7v_o9Mme4Q", slug: "time-equals-money" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Dawn of Eternal Night", youtubeId: "0Fj8kA93ddc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Cyboogie", youtubeId: "_un9PYsE1_g" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Vegemite", youtubeId: "6Inr7FKKWLI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "30 Past 7", youtubeId: "j7EU7GVjyRA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Welcome To An Altered Future", youtubeId: "fFeFsYXl-moKXphD" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Open Water", youtubeId: "2JOOZLNVc_ZbwmuW" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Mars For The Rich", youtubeId: "h-anfqu_e4Xxb-yi" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hog Calling Contest", youtubeId: "hrpQl4CLRX4"},
  { artist: "King Gizzard and the Lizard Wizard", name: "Dustbin Fletcher", youtubeId: "KxUZA5clWUrNfQmS" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Ice V", youtubeId: "ydeV1_8pM4o" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Change To", youtubeId: "WMP8PJtqM2o" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hell", youtubeId: "OmS5miyHxr9puTPw" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sleep Drifter", youtubeId: "8XW8yofuGao" },
  { artist: "King Gizzard and the Lizard Wizard", name: "I'm Sleepin' In", youtubeId: "qk-0WfvTDLRS2xmZ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Worship Satan To", youtubeId: "1em1dy2yPPA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Minimum Brain Size", youtubeId: "QTXFeuUCFaU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Plasma", youtubeId: "QaC2ssj-6Xw" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Yours", youtubeId: "50uxqPUJiDA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Aerodynamic", youtubeId: "CFE5gMDKYXM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sweet Talking", youtubeId: "SvCJKoYouqA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "It's Got Old", youtubeId: "0nwS2Fux_6fxMM5q" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Some Of Us", youtubeId: "QBqX7fEwtWk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Land Before Timeland", youtubeId: "yTm7wzsoU6I" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Perihelion", youtubeId: "BldV5V5jGKgpCbMr" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Acarine", youtubeId: "9iQPylX7gQA03ckl" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Castle In The Air", youtubeId: "1LYrTvPAGWU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Life Is Cool", youtubeId: "H1docw-O0uI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Billabong Valley", youtubeId: "mTN5OE3AYOyWHAYD" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Searching...", youtubeId: "gkNbgF1Tgcg" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "The Spider And Me", youtubeId: "Y-Ks5VEVCfiiHmBA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Raw Feel", youtubeId: "a8MBLs7yQyk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Gaia", youtubeId: "dPXObWXgvbw" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "A Journey To (S)hell", youtubeId: "1_k61sqXrN_MNAWd", slug: "a-journey-to-s-hell" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Think Existentially To", youtubeId: "a9BMNrUtd5I" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Marble", youtubeId: "1XW7BUEsHuY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Greenhouse Heat Death", youtubeId: "5Npv-UvtJ3w" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Doom City", youtubeId: "T6sh3OnmdYaunzo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Mycelium", youtubeId: "RfV5gXIZPEo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Donkey Jam", youtubeId: "y0lFm7EjW80" },
  { artist: "King Gizzard and the Lizard Wizard", name: "If Not Now, Then When?", youtubeId: "K31OW7ZdRGQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Boogieman Sam", youtubeId: "-kE1S9olY6A" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Horology", youtubeId: "cRyjHYaZwnw" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sad Pilot", youtubeId: "LvSPhF_bW8U" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hot Water", youtubeId: "gS1jOp0sAkM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Oddments", youtubeId: "hEscvNM4puBbLIib" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The River", youtubeId: "PUZn1I6llJs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Wah Wah", youtubeId: "xpglzBGVJ2U" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Deserted Dunes Welcome Weary Feet", youtubeId: "cw3hIGgFJHs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Presumptuous", youtubeId: "m-2CDCALDeU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Im In Your Mind", youtubeId: "mUFicFRuDnU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Robocop", youtubeId: "aYlRh-mltz0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Lord Of Lightning", youtubeId: "DC9Bcn8AbLgfKFhL" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Not Enough Time... Land", youtubeId: "0MyoCoEKDmo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Timeland", youtubeId: "zZTsaoyunHI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sea Of Trees", youtubeId: "WxvzCc05eX0-ExD1" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Paper Mache", youtubeId: "JDv6eO9XBGs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Satan Speeds Up", youtubeId: "R0-DlJ7V6fg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Danger $$$", youtubeId: "JZNpwNX85oSjc1k2", slug: "danger-money" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Tomb/Beach", youtubeId: "pSdvjBJUHrM", slug: "tomb-beach" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Dirt", youtubeId: "3pE3wFIYfQk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Wholly Ghost", youtubeId: "wdCsvbllDuE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Soy-Protein Munt Machine", youtubeId: "9ondsvLmjX_6Xaey" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Interior People", youtubeId: "LzcWTjY3b8Q" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Dreams", youtubeId: "DN-Sr6nPqNo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Gilgamesh", youtubeId: "0E-dnvgbZL4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Funeral", youtubeId: "EcNuK43WK4U" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Great Chain Of Being", youtubeId: "fvCAXS_MB6RU7Khh" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Catching Smoke", youtubeId: "4L3-HOdMeuM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Trailer Park Kid", youtubeId: "vGHTWpW4ROA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The God Man's Goat Lust", youtubeId: "iNrIvTp3tGAodSdZ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Phantom Island", youtubeId: "1lR8VLt1Xlk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Demo No. 79", youtubeId: "CTG8splNR3E" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Short Change", youtubeId: "cbv5ItSNKQk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Mariposa", youtubeId: "mVRAXWgyNtU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Crying", youtubeId: "f16ct6kuZ0d6uGZN" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Theia", youtubeId: "3jnsD-fEHdY" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Sketches of Brunswick East I", youtubeId: "RNLc3hM9BNd9We0a" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Cloud of Dread", youtubeId: "B_dProTs6LE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Scared Of Christmas", youtubeId: "jj1A7h2-MV4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "O.N.E.", youtubeId: "lkZd2lBQb2c" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Flamethrower", youtubeId: "wPKmEUnj3IE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Field of Vision", youtubeId: "S2wZcdW1LKE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Antarctica", youtubeId: "mcGehIgTnhU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Ambergris", youtubeId: "cMSTPowdj7w" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Gondii", youtubeId: "ATjsNT_X_70" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Mother Hen", youtubeId: "lWkRl0U3HuM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Converge", youtubeId: "bVrxd7YZ_Ng" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Black Hot Soup", youtubeId: "daz_doXNAB4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Year Of Our Lord", youtubeId: "02a9cmO1FI4oD3w5" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Deadstick", youtubeId: "H7t2FL1SRaE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Extinction", youtubeId: "QefffIbeAcc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Cellophane", youtubeId: "U68lcZygXlo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Lava", youtubeId: "_L_SR9XIiNs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Fort Whipple", youtubeId: "xuC0WMZ5TQJzR0eg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "East West Link", youtubeId: "uQlS_dN0CXs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Invisible Face", youtubeId: "ekXb74bUbRM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Infinite Rise", youtubeId: "S20JGdyeuE0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Hungry Wolf Of Fate", youtubeId: "onsgnXa2T8c" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Burn Money To", youtubeId: "r4XCSYNIScQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hell's Itch", youtubeId: "3aUKofcKfmg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Motor Spirit", youtubeId: "U0AcBryPUxY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Let Me Mend The Past", youtubeId: "zDXDNiHJLF51jIJ7" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Mirage City", youtubeId: "mkMYHBZibj4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Persistence", youtubeId: "K14JkFfWUzc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Set", youtubeId: "XCCzPDne-dQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Moses", youtubeId: "infJi0wqcHE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Fury", youtubeId: "mqftZ7PlYnk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Straws In The Wind", youtubeId: "ioqgrYorhkU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Eat Bananas To", youtubeId: "W04EmIyRXIU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Grow Wings and Fly", youtubeId: "TWUIsRsvJC8" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Rats In The Sky", youtubeId: "EdvoDnPySLA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Dust In The Wind", youtubeId: "1fGTtXBObJIIAfm3" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Empty", youtubeId: "GGO8g-njNpA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Time = Fate", youtubeId: "YZ7jzxbbEzY", slug: 'time-equals-fate' },
  { artist: "King Gizzard and the Lizard Wizard", name: "Venusian 1", youtubeId: "hf5SxRx1HLAVofh5" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Crumbling Castle", youtubeId: "uLP8rFrL1W0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Honey", youtubeId: "dG9917nyJXA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Cookies", youtubeId: "F7Lvxok2KYM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "I'm Not A Man Unless I Have A Woman", youtubeId: "6VgKwen5VLY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Lonely Cosmos", youtubeId: "Vy5xatxnPgU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Superposition", youtubeId: "GYihTVgkA_zGuf3v" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Red Smoke", youtubeId: "pLdLxt4IkcM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Bitter Boogie", youtubeId: "y298za65kcg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Beginner's Luck", youtubeId: "YEwvnKYpDNZhX_z1" },
  { artist: "King Gizzard and the Lizard Wizard", name: "See Me", youtubeId: "BNJiUlW2-pw" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Slow Jam 1", youtubeId: "fb3tBvyXcT4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Nein", youtubeId: "PLfhjrUI_uI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Wheel", youtubeId: "3iwjB7V73qvmT576" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Cranes, Planes, Migraines", youtubeId: "eY_6Ljn8tYL0-otz" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Flight b741", youtubeId: "QwTIRYo7aBY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Stressin'", youtubeId: "1HizV1S0_rHOsC92" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Black Tooth", youtubeId: "zokGGBuKpyw" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Rolling Stoned", youtubeId: "s6nDrCHmj4b-O27n" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Her And I (Slow Jam 2)", youtubeId: "PVkUMbht84s" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hate Dancin'", youtubeId: "znmEqLn9bR8" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Gamma Knife", youtubeId: "5zhjnBwTCxk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Worm", youtubeId: "DZYN83CjAMc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Evil Star", youtubeId: "mC6u9FkjnqouGpTe" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Sketches Of Brunswick East III", youtubeId: "HvCRVfNsrxpkiU7q" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Altered Beast I", youtubeId: "z0K0WDyUkk31fx_B" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Footy Footy", youtubeId: "XT4LKJmYYLedOPuC" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Cut Throat Boogie", youtubeId: "Tnt-_niKRqvGyQrq" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Candles", youtubeId: "fGXvND_vE-M" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Dripping Tap", youtubeId: "oDMldn7hFZo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Silent Spirit", youtubeId: "IhH0wJMI9dY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Fishing For Fishies", youtubeId: "beIDKFwXam0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Most Of What I Like", youtubeId: "9Z5GQnL3-cU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Tea And Jam", youtubeId: "oAmyntteie4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Superbug", youtubeId: "PZLZDhsrsGEBAzhZ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "MTV", youtubeId: "gsyZ49GsO_g" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Tetrachromacy", youtubeId: "EMCnTig3IaE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "BIT BIT BIT BIT BIT BIT BIT", youtubeId: "lmXvWj94U1I" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Blue Horse", youtubeId: "MlEj2rSIu7E" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Alluda Majaka", youtubeId: "rCWfdlG5nW8vLcXq" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Organ Farmer", youtubeId: "2TBvQBuWRR4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Lean Woman Blues (T.Rex cover)", youtubeId: "_zxvigx0eFk", slug: 'lean-woman-blues' },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "The Book", youtubeId: "zrZktrZFAW-lyfBi" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Altered Beast III", youtubeId: "f5CYlPDn8mEXa2To" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Cruel Millennial", youtubeId: "2KldOalVewjhlo1y" },
  { artist: "King Gizzard and the Lizard Wizard", name: "German Rock n' Rolle", youtubeId: "vcyyDumgqdU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Lonely Steel Sheet Flyer", youtubeId: "HPv-p6NQNAk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Last Oasis", youtubeId: "XF_eiMLG9Ho" },
  { artist: "King Gizzard and the Lizard Wizard", name: "This Thing", youtubeId: "JRzQSPGe-GEKbLb9" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Eternal Return", youtubeId: "KwZ8n0fkZmA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Acrid Corpse", youtubeId: "d_OzSbKri3l8rfiU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sense", youtubeId: "5XtSEKBp2Uo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Music To Eat Pond Scum To", youtubeId: "4302MhKBE0U" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Elbow", youtubeId: "AJk2WoF174KhUd4K" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Balrog", youtubeId: "EwKMh9gNmSfkTikb" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Supreme Ascendancy", youtubeId: "4LEVIOLaWN8" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hey There", youtubeId: "e1Ef5WyAohA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Paper Mache Dream Balloon", youtubeId: "lci8-n8K394" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The 10th Boogie", youtubeId: "0vCUU3nfcrI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Oddlife", youtubeId: "jYOdebIv53E" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Life / Death", youtubeId: "sUGGy18U3S5t9VP1" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Ants and Bats", youtubeId: "yF9so14vBwU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Venusian 2", youtubeId: "9CmnEPI5Cr8OltSR" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Road Train", youtubeId: "Tbwym5FXSFo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Quarantine", youtubeId: "O9nCZgYFYmaZuLKy" },
  { artist: "King Gizzard and the Lizard Wizard", name: "ABABCd", youtubeId: "97D1M1K_G_jM_WHo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Trapdoor", youtubeId: "JQvIvKG_ktY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Homeless Man In Adidas", youtubeId: "NuXDPEtNTbvv53w0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Melting", youtubeId: "2GGD2AkSCOpTMxau" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Dead Beat", youtubeId: "_zTrV9uEq7w" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Raid", youtubeId: "USJpMfGNkZs1Xecp" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Am I In Heaven?", youtubeId: "jDf4lju69LY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Digital Black", youtubeId: "ZTQOEj8G6stbl6sd" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Le Risque", youtubeId: "Ik-gBAlEbQY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Brassicas", youtubeId: "TCEianf0KB8" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Uh Oh, I Called Mum", youtubeId: "PPLNhKVP64MEPub8" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Inner Cell", youtubeId: "oek7d-6KtxU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Muckraker", youtubeId: "82C_x1tZ2JM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Smoke And Mirrors", youtubeId: "Zh-NTKaPXiQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Evil Death Roll", youtubeId: "IUB-ex-ClvQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Supercell", youtubeId: "U8gKLveIvuk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Mr. Beat", youtubeId: "UAvnER-tSx8" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Alter Me II", youtubeId: "lSgjsAlKUmKE1CrV" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Blame It On The Weather", youtubeId: "peSrD_GwAlI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Dragon", youtubeId: "9CzqotsTGss" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Pleura", youtubeId: "swxnoxP6WH0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Garden Goblin", youtubeId: "CoDTiOXbAUY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Let It Bleed", youtubeId: "VZOWCU8NAqqPIs8l" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Eyes Like The Sky", youtubeId: "IDF5tb3uVqsiq8qz" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Head On/Pill", youtubeId: "23vVIgTMZFU", slug: 'head-on-pill' },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Bird Song", youtubeId: "FFDfqhsuWu-7GPGb" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Plastic Boogie", youtubeId: "gOhMypF0QdAH1rut" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Spacesick", youtubeId: "KuYSTcQdo64" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Daily Blues", youtubeId: "_TN5WQLGaA0" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "You Can Be Your Silhouette", youtubeId: "TbaXCXirkjRCrq1t" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Shanghai", youtubeId: "-01sgnVgkRc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Flying Fishie", youtubeId: "995lTfyo5UM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Panpsych", youtubeId: "TA1sJw5ZL5o" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Altered Beast IV", youtubeId: "YkOri0-ow1dwpPCd" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Down The Sink", youtubeId: "TX-Sr9EXuHYypEsd" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Big Fig Wasp", youtubeId: "eCkMxcEf7jI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Parking (Live in Brussels '19)", youtubeId: "G_1-54XNzhCgBv0e", slug: "parking" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Space Junk", youtubeId: "T6T0M22_BFw" },
  { artist: "King Gizzard and the Lizard Wizard", name: "People-Vultures", youtubeId: "FAyJFLsRWEc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Change", youtubeId: "3XAhEUHt3zY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "God Is Calling Me Back Home", youtubeId: "U3sE3GlvxDRg1Z7o" },
  { artist: "Tropical Fuck Storm/King Gizzard and the Lizard Wizard", name: "Satanic Slumber Party Part 1 (The Chairmans Portrait)", youtubeId: "BrPzR6Hu5Zg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Venusian 2", youtubeId: "dtspnWoRFbw" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Some Context", youtubeId: "lAPlCeiOQvwe-FLU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Demo No. 67", youtubeId: "QEylT9Qg-MI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Bone", youtubeId: "RoiqNNajdcc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Ontology", youtubeId: "S55EKp8atjs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Reticent Raconteur", youtubeId: "P2KQFwAkuF9IaMdk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Gila Monster", youtubeId: "YQX2CsMCB9M" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Willoughby's Beach", youtubeId: "A9oieSzxo2fgwSF4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "9 TET", youtubeId: "n_V6WQevAUQ" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Guns & Horses", youtubeId: "0KwmPGpdl-csRhD-", slug: 'guns-and-horses' },
  { artist: "King Gizzard and the Lizard Wizard", name: "Murder Of The Universe", youtubeId: "VkyJv9akVNIoBaa7" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Anamnesis", youtubeId: "zDeAXWwTo571uIaT" },
  { artist: "King Gizzard and the Lizard Wizard", name: "No Body", youtubeId: "9XiMzrq1AcI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Cold Cadaver", youtubeId: "M71mQt-4pzo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Flying Microtonal Banana", youtubeId: "Y1-iqaG0cZbDAfbr" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Automation", youtubeId: "kwNH2RhEBgY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Evil Man", youtubeId: "7rExTyw-1VEoJ9x_" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "D-Day", youtubeId: "aDFbsIZYJ2ZamAln" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Ataraxia", youtubeId: "t23If5O_AdI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Drum Run", youtubeId: "Wqf2iHy7CLYeu_-x" },
  { artist: "Tropical Fuck Storm/King Gizzard and the Lizard Wizard", name: "Satanic Slumber Party Part 3 (Hoof And Horn)", youtubeId: "L_8AJcXH_Fk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Nuclear Fusion", youtubeId: "4MFVhqcRpN4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Astroturf", youtubeId: "ql_z7t6WGPg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Kepler-22b", youtubeId: "gfvEodNPQGs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "A New World", youtubeId: "asZS3nBAtjrvtFsD" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Chang'e", youtubeId: "cxe3V-06UAU" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Sketches Of Brunswick East II", youtubeId: "SQ-fIiECPgCy7tJi" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Im Not In Your Mind", youtubeId: "RL1iyfnCx8k" },
  { artist: "King Gizzard and the Lizard Wizard", name: "God Is In The Rhythm", youtubeId: "w5KHjQMTwIk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Predator X", youtubeId: "4DqKF3Hu81g" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Kelebek", youtubeId: "IM_Up9T-0QM" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Floating Fire", youtubeId: "iKkSqs9thBY61awF" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Killing Ground", youtubeId: "9TCjlkOq9sSwOy9x" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Rattlesnake", youtubeId: "Q-i1XZc8ZwA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Gliese 710", youtubeId: "KO_MYeVy-QE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sea of Doubt", youtubeId: "ZcPrx7haw2g" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Alter Me I", youtubeId: "UhIEZ4BrFA9069Rs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Stoned Mullet", youtubeId: "IF5gT8dfZ8XT6r_G" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Intrasport", youtubeId: "05s4dEcAgMI" },
  { artist: "King Gizzard and the Lizard Wizard with Mild High Club", name: "Countdown", youtubeId: "MPl4WLM55Vg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Embryo", youtubeId: "Y1ndjhKCvok" },
  { artist: "King Gizzard and the Lizard Wizard", name: "High Hopes Low", youtubeId: "N83JYtLQzwXDofyU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Crookedile", youtubeId: "o_LUMFtsxYS8m-1_" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Barefoot Desert", youtubeId: "hGLPR1pJBR_VJ8N0" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Swan Song", youtubeId: "1ptD_ooY174" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Hot Wax", youtubeId: "s8azlP-FgHs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Party Potential", youtubeId: "7Onx4fm1H48" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Stevie Ray Horn", youtubeId: "kLCfBpu-tmI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Loyalty", youtubeId: "GDFcxVNoTJU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sam Cherry's Last Shot", youtubeId: "H9X9yPnBls7wDRfU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Fried", youtubeId: "4z5iumke1Ds" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sleep", youtubeId: "WvUvZp7hwTU" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Open My Eyes (Nazz cover)", youtubeId: "zrlflcC4Fj0", slug: 'open-my-eyes' },
  { artist: "King Gizzard and the Lizard Wizard", name: "Lukey's Brain", youtubeId: "jJTGJlQ8g8U" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Ya Love", youtubeId: "sbUvwyokv_E" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Static Electricity", youtubeId: "lOhj8z1ZxWg" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Magenta Mountain", youtubeId: "1sRCEGf9I1g" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Butterfly 3000", youtubeId: "dVElzsCmHPs" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Iron Lung", youtubeId: "Njk2YAgNMnE" },
  { artist: "King Gizzard and the Lizard Wizard", name: "12 Bar Bruise", youtubeId: "xhT8p1fjcvaFyYPS" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Magma", youtubeId: "Fg7reWLQtd4" },
  { artist: "King Gizzard and the Lizard Wizard", name: "The Fourth Colour", youtubeId: "mTZ6pBwCfYY" },
  { artist: "King Gizzard and the Lizard Wizard", name: "2.02 Killer Year", youtubeId: "gvLVX25-Go4", slug: '2-02-killer-year' },
  { artist: "King Gizzard and the Lizard Wizard", name: "Han-Tyumi, The Confused Cyborg", youtubeId: "Rs0cBnWr0SxktBYr" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Lunch Meat", youtubeId: "_N_vKxkb_lv1b8xm" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Pipe-Dream", youtubeId: "LLO-MHYfjiTuWs8z" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sadie Sorceress", youtubeId: "M5loDs9vMeA" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Real's Not Real", youtubeId: "Yko5vki1BJOSvZ-p" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Witchcraft", youtubeId: "C4WzPHaOS2M" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Sleepwalker", youtubeId: "i6psKZRi9OW6Jjdr" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Alter Me III", youtubeId: "wEa6xw0r9ynkLuEO" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Altered Beast II", youtubeId: "g7u_URprUMzeoiMo" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Self-Immolate", youtubeId: "cmAlQvDQGoI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "A Brief History of Planet Earth (Live in London, Berlin, Utrecht and Barcelona '19)", youtubeId: "DUY3u1sdcom6Vu5C", slug: "a-brief-history-of-planet-earth" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Robot Stop", youtubeId: "9p_Si21ig7c" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Summer!", youtubeId: "la72E_i87Dc" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Polygondwanaland", youtubeId: "p9QhRKIVlJI" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Anoxia", youtubeId: "i2f1BAxPuaq_De8U" },
  { artist: "King Gizzard and the Lizard Wizard", name: "All Is Known", youtubeId: "CxlUl6dVxPk" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Garage Liddiard", youtubeId: "awgvBvTCFDLUqDhH" },
  { artist: "King Gizzard and the Lizard Wizard", name: "Float Along – Fill Your Lungs", youtubeId: "AG_XjskSmXVzjCFu", slug: "float-along-fill-your-lungs-2" }
];
